"""Content intake pipeline — ingest, normalize, and synthesize external content."""

from distill.intake.models import (
    BrowserIntakeConfig,
    ContentItem,
    ContentSource,
    DailyIntakeContext,
    DailyIntakeEntry,
    GmailIntakeConfig,
    IntakeConfig,
    IntakeMemory,
    IntakeRecord,
    IntakeState,
    LinkedInIntakeConfig,
    RSSConfig,
    RedditIntakeConfig,
    SeedIdea,
    SessionIntakeConfig,
    SubstackIntakeConfig,
    TwitterIntakeConfig,
    YouTubeIntakeConfig,
)
from distill.intake.services import (
    IntakeSynthesizer,
    SeedStore,
    archive_items,
    build_daily_index,
    classify_items,
    cluster_items,
    enrich_tags,
    extract_entities,
    load_intake_memory,
    load_intake_state,
    prepare_daily_context,
    render_clustered_context,
    save_intake_memory,
    save_intake_state,
)

# enrich_items lives in services as well but has a common alias
from distill.intake.services import enrich_items as enrich_fulltext

__all__ = [
    "BrowserIntakeConfig",
    "ContentItem",
    "ContentSource",
    "DailyIntakeContext",
    "DailyIntakeEntry",
    "GmailIntakeConfig",
    "IntakeConfig",
    "IntakeMemory",
    "IntakeRecord",
    "IntakeState",
    "IntakeSynthesizer",
    "LinkedInIntakeConfig",
    "RSSConfig",
    "RedditIntakeConfig",
    "SeedIdea",
    "SeedStore",
    "SessionIntakeConfig",
    "SubstackIntakeConfig",
    "TwitterIntakeConfig",
    "YouTubeIntakeConfig",
    "archive_items",
    "build_daily_index",
    "classify_items",
    "cluster_items",
    "enrich_fulltext",
    "enrich_tags",
    "extract_entities",
    "load_intake_memory",
    "load_intake_state",
    "prepare_daily_context",
    "render_clustered_context",
    "save_intake_memory",
    "save_intake_state",
]
